### ISSUE TITLE
pkg:build consumer

### ISSUE THREAD

**Issue by thosakwe** [thosakwe/dmake#6]

**Comment by kevmoo** [comment]
I was just going to file an issue here – why this and not pkg:build and friends?

**Comment by thosakwe** [comment]
This repo was more of an exercise than anything - I never ended up actually
using it, and probably never will.

Taught me a little bit about build systems, though, haha!

**Comment by kevmoo** [comment]
No worries.

If you plan to completely drop https://pub.dartlang.org/packages/dmake,
file a 'discontinue' request on the package site so we hide it from
searches!

Just click the "open issue" at the bottom of the page!

**Comment by thosakwe** [comment]
Sounds good, thanks!
